# Generated by Django 5.1.6 on 2025-04-14 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0001_initial"),
        ("prompts", "0001_initial"),
        ("rubrics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correction",
            name="correction",
        ),
        migrations.AddField(
            model_name="correction",
            name="folder_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="correction",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrections",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="correction",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrections",
                to="prompts.prompt",
            ),
        ),
        migrations.AlterField(
            model_name="correction",
            name="rubric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrections",
                to="rubrics.rubric",
            ),
        ),
    ]
