# Generated by Django 5.1.6 on 2025-04-18 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "corrections",
            "0002_remove_correction_correction_correction_folder_path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="last_ejecution_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
