# Generated by Django 5.1.6 on 2025-04-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0003_correction_last_ejecution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correction",
            name="last_ejecution_date",
            field=models.DateTimeField(null=True),
        ),
    ]
