# Generated by Django 5.1.6 on 2025-04-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0004_alter_correction_last_ejecution_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="runnung",
            field=models.BooleanField(default=False),
        ),
    ]
