# Generated by Django 5.1.6 on 2025-04-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0005_correction_runnung"),
    ]

    operations = [
        migrations.RenameField(
            model_name="correction",
            old_name="runnung",
            new_name="running",
        ),
    ]
