# Generated by Django 5.1.6 on 2025-05-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0006_rename_runnung_correction_running"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="model_temp",
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name="correction",
            name="model_top_k",
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name="correction",
            name="model_top_p",
            field=models.FloatField(default=1.0),
        ),
    ]
