# Generated by Django 5.1.6 on 2025-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0007_correction_model_temp_correction_model_top_k_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correction",
            name="llm_model",
            field=models.CharField(default="llama3", max_length=255),
        ),
        migrations.AlterField(
            model_name="correction",
            name="model_temp",
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name="correction",
            name="model_top_p",
            field=models.FloatField(default=0.9),
        ),
    ]
