# Generated by Django 5.1.6 on 2025-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0008_alter_correction_llm_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="output_format",
            field=models.CharField(default="", max_length=5),
        ),
    ]
