# Generated by Django 5.1.6 on 2025-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0009_correction_output_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correction",
            name="output_format",
            field=models.CharField(
                choices=[("json", "json"), ("text", "")], default="text", max_length=255
            ),
        ),
    ]
