# Generated by Django 5.1.6 on 2025-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0010_alter_correction_output_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="time_last_ejecution",
            field=models.IntegerField(default=0),
        ),
    ]
