# Generated by Django 5.1.6 on 2025-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0011_correction_time_last_ejecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="model_context_length",
            field=models.IntegerField(default=2048),
        ),
    ]
