# Generated by Django 5.1.6 on 2025-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0012_correction_model_context_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correction",
            name="output_format",
            field=models.CharField(default="text", max_length=10),
        ),
    ]
